# Configurações do jogo
LARGURA = 1280
ALTURA = 720
FPS = 60

# Configurações do jogador
JOGADOR_INICIO_X = 400
JOGADOR_INICIO_Y = 500
TAMANHO_JOGADOR = 0.35
VELOCIDADE_JOGADOR = 8
DESLOCAMENTO_ARMA_X = 45
DESLOCAMENTO_ARMA_Y = 10

# Configurações das balas
TEMPO_TIROS = 20
ESCALA_BALA = 1.4
VELOCIDADE_BALA = 15
TEMPO_VIDA_BALA = 750