# Configurações do jogo
LARGURA = 1280
ALTURA = 720
FPS = 60

# Configurações do jogador
JOGADOR_INICIO_X = LARGURA // 0.8
JOGADOR_INICIO_Y = ALTURA // 0.5
TAMANHO_JOGADOR = 0.35
VELOCIDADE_JOGADOR = 2
DESLOCAMENTO_ARMA_X = 45
DESLOCAMENTO_ARMA_Y = 10

# Configurações das balas
TEMPO_TIROS = 20
ESCALA_BALA = 1.4
VELOCIDADE_BALA = 10
TEMPO_VIDA_BALA = 750

#configuração inimigo
VELOCIDADE_INIMIGO = 1